### ISSUE TITLE
Determine project toolchain

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand-shuffle#1]
Create React App is no longer maintained, so a suitable alternative must be selected.

**Comment by jeremyckahn** [comment]
@lstebner floated the idea of using https://parceljs.org/ [on Discord](https://discord.com/channels/714539345050075176/714539345637408793/1136713834514612245). Another moden option is https://vitejs.dev/. I'm not familiar enough with either to have a preference yet.

@lstebner, what about ParcelJS appeals to you?

**Comment by lstebner** [comment]
parceljs has just been ridiculously easy to use. everything i've wanted has just worked (css modules, react, unit testing, tree shaking, local server, etc) which has never been the case for me in a modern js stack. there is no babel to deal with, no webpack, and freedom to organize code any way you want. i actually didn't try vite but it was also recommended as an alternative to me (by josh), i did however switch from jest to vitest and it's been great. 

i think parcel is actually so simple you can safely try it out and all the code you write would be compatible with another system if you wanted to move it

**Comment by jeremyckahn** [comment]
Thanks for sharing your perspective, @lstebner! ParcelJS seems like a great option. I explored ParcelJS and Vite on my own, and I think they'd both work well for us. ParcelJS seems a bit less opinionated, whereas Vite seems like a more direct replacement for Create React App.

Let's go with ParcelJS for now. I think your experience with it will be valuable for this project. If we run into issues, we can always revisit. I'll get it set up! 🙂
